version: 2.1
jobs:
  node:
    working_directory: ~/react-native
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/react-native
          paths:
            - node_modules
         
  android-alpha:
    working_directory: ~/react-native/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/react-native

      - attach_workspace:
          at: ~/react-native

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      
      - run:
          name: fastlane android alpha
          command:
            bundle exec fastlane alpha

      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
    
  android-beta:
    working_directory: ~/react-native/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/react-native

      - attach_workspace:
          at: ~/react-native

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      
      - run:
          name: fastlane android beta
          command:
            bundle exec fastlane beta

workflows:
  node-android:
    jobs:
      - android-hold:
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - node:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - android-alpha:
          requires:
            - node
            - android-hold
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/